### ISSUE TITLE
FirebaseApp is not initialized

### ISSUE THREAD

**Issue by linhnv106** [dandar3/android-google-firebase-database#1]
Hi @dandar3 , I got this message :
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process  Make sure to call FirebaseApp.initializeApp(Context) first.
I've already called :  FirebaseApp.initializeApp(this) on onCreate() method

**Comment by dandar3** [comment]
can you please give me the entire stack trace and any other exception before or below that please, thank you.

I assume you followed the indications for similar situations like [Integrating Firebase Cloud Messaging](http://dandar3.blogspot.com/2017/01/eclipse-integrating-firebase-messaging.html) and you have manually converted google-services.json into a res\values\google-services.xml as per [Processing the JSON file](https://firebase.google.com/docs/reference/gradle/#processing_the_json_file).

I'm a bit puzzled cause according to Firebase documentation:
https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp

> For a vast majority of apps, FirebaseInitProvider will handle the initialization of Firebase for the default project that it's configured to work with, via the data contained in the app's google-services.json file. This ContentProvider is merged into the app's manifest by default when building with Gradle, and it runs automatically at app launch. No additional lines of code are needed in this case.

and while we don't have a Gradle task to generate the entries in the AndroidManifest.xml or generate the values.xml from the JSON file, you can do that manually as per the above and then everything else should work as expected.

I'll give it a try myself later this evening and build a sample Firebase Database app and let you know if I find any problems.

**Comment by linhnv106** [comment]
@dandar3 thank you very much, I had to use support-v4 and support-v7 lib to our project, and it works.

**Comment by dandar3** [comment]
Great stuff. I warmly recommend importing a project as a Team Set (all projects should have this feature, see the link in their README.md). Plus see the videos at the end of the `dandar3/android-google-firebase-README` project, should make life a lot easier to download a project and to upgrade later on.
